# Generated by Django 5.0.3 on 2024-04-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.FileField(blank=True, null=True, upload_to='preview/'),
        ),
    ]
