# Generated by Django 5.0.3 on 2024-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0002_course_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='LastUpdated',
        ),
        migrations.AddField(
            model_name='course',
            name='Topic_to_be_covered',
            field=models.TextField(blank=True, null=True),
        ),
    ]
