# Generated by Django 5.0.3 on 2024-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0004_alter_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='course/'),
        ),
    ]
